import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.scss";

const gothamBook = localFont({
  src: '../../public/fonts/gotham_book.otf',
})

export const metadata: Metadata = {
  title: "Bilnk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gothamBook}`}>
        {children}
      </body>
    </html>
  );
}
